### ISSUE TITLE
Port Twitch Commands

### ISSUE THREAD

**Issue by poydok** [JoshPaulie/goonbot4#1]
>> Loop.(nested)
>> request initiated
        >> request_null ?
        >> request => "/(insert content channel)"
>> output => url of channel

Hello technomancer overlord I humbly request the ability to fast travel from discord straight to my favorite content creators via GB4. /t1, /hob, /poydok, etc. Thank you based god @JoshPaulie

**Comment by poydok** [comment]
Nice job  adding to the Milestone "Fully* port GB3 to GB4"

**Comment by JoshPaulie** [comment]
Update: I worked on this last night, couldn't get it to work.

Now I'm in the **existential dread** part of development. This is good news, because the next step is me figuring it out

Attempt ➡️ fail ➡️ pure panic ➡️ debug ➡️ repeat 🔁

**Comment by poydok** [comment]
It is all part of the process. Let the dread flow through you young one. *pog*

**Comment by JoshPaulie** [comment]
https://github.com/JoshPaulie/goonbot4/commit/64eee46e41a66537a0e1939ae12648a6f0061baf

Implemented! 🦝

**Comment by poydok** [comment]
Great work! I knew you could do it! it is a lot smoother than GB3. Issue Status: Closed!

**Comment by poydok** [comment]
twitch.tv/doaenel
for youtube you could do Synapse and Northernlion and DanGheesling :)
