### ISSUE TITLE
Port youtube commands

### ISSUE THREAD

**Issue by JoshPaulie** [JoshPaulie/goonbot4#4]
Dr. Soup

**Comment by poydok** [comment]
I like this one. You could even add Northernlion! ORRRR Synapse!!! very pog

**Comment by JoshPaulie** [comment]
I'd love to expand the amount of channels! I need to be wary because ever command adds to the long list, but I think I have a solution for that.

If you think of any others let me know

**Comment by JoshPaulie** [comment]
Big ups!
