### ISSUE TITLE
Figure out how to separate NL and DannyG YT and TTV commands

### ISSUE THREAD

**Issue by JoshPaulie** [JoshPaulie/goonbot4#6]
> twitch.tv/doaenel
> for youtube you could do Synapse and Northernlion and DanGheesling :)

_Originally posted by @poydok in https://github.com/JoshPaulie/goonbot4/issues/1#issuecomment-1025055265_

So the issue is both Northernlion and DanGheesling are already twitch commands, with corresponding names.

**Comment by poydok** [comment]
Thanks boo!
